-- GENERADO por db/tools/generar_seed.py desde data/catalogo_plantillas_negocios.xlsx
-- No editar a mano: cambia el Excel o el script y vuelve a generar.

insert into catalogo.plan (codigo, nombre, precio_mensual, orden, limites) values
  ('gratis', 'Gratis', 0.00, 1, '{"usuarios": 1, "productos": 50}'::jsonb),
  ('emprendedor', 'Emprendedor', 7.99, 2, '{"usuarios": 2}'::jsonb),
  ('negocio', 'Negocio', 17.99, 3, '{"usuarios": 5}'::jsonb),
  ('pro', 'Pro', 29.99, 4, '{"usuarios": 15, "sucursales": 3}'::jsonb)
on conflict (codigo) do update set nombre = excluded.nombre, precio_mensual = excluded.precio_mensual, orden = excluded.orden, limites = excluded.limites;

insert into catalogo.modulo (codigo, nombre, descripcion, tipo, fase) values
  ('M01', 'Ventas (punto de venta)', 'Registrar ventas rápidas, métodos de pago, descuentos, comprobante por WhatsApp o impreso', 'nucleo', 1),
  ('M02', 'Caja', 'Apertura y cierre de caja, arqueo, descuadres, ingresos y retiros de efectivo', 'nucleo', 1),
  ('M03', 'Gastos', 'Registro de gastos por categoría', 'nucleo', 1),
  ('M04', 'Inventario', 'Stock automático (compra suma, venta resta), alertas de stock bajo, conteos', 'activable', 1),
  ('M05', 'Variantes', 'Tallas, colores y presentaciones por producto', 'activable', 1),
  ('M06', 'Venta por peso/medida', 'Venta por kilo, libra, litro, metro, quintal; balanza', 'activable', 1),
  ('M07', 'Código de barras', 'Lectura EAN-13/UPC-A con cámara o lector, impresión de etiquetas', 'activable', 1),
  ('M08', 'Recetas e insumos', 'El producto final descuenta insumos; costo por plato o producto', 'activable', 2),
  ('M09', 'Mesas y comandas', 'Mapa de mesas, cuentas abiertas, comandas a cocina, división de cuenta', 'activable', 2),
  ('M10', 'Pedidos y delivery', 'Pedidos para llevar o a domicilio, estados, repartidor', 'activable', 2),
  ('M11', 'Citas y agenda', 'Agenda por profesional, recordatorios por WhatsApp', 'activable', 2),
  ('M12', 'Servicios y comisiones', 'Catálogo de servicios, comisión por empleado', 'activable', 2),
  ('M13', 'Órdenes de trabajo', 'Recepción de equipo o vehículo, diagnóstico, repuestos, mano de obra, estado', 'activable', 2),
  ('M14', 'Fiado / cuentas por cobrar', 'Deudas de clientes, abonos, recordatorios automáticos de cobro', 'activable', 1),
  ('M15', 'Proveedores y compras', 'Proveedores, órdenes de compra, compras que actualizan stock y costo', 'activable', 1),
  ('M16', 'Lotes y caducidad', 'Lote y fecha de vencimiento por producto, alertas', 'activable', 2),
  ('M17', 'Listas de precios', 'Precio minorista, mayorista, por volumen o por cliente', 'activable', 2),
  ('M18', 'Catálogo online', 'Catálogo compartible con pedidos que entran al POS', 'activable', 3),
  ('M19', 'Facturación electrónica SRI', 'Factura, nota de crédito, retención; firma y transmisión inmediata al SRI', 'nucleo', 1),
  ('M20', 'Empleados y permisos', 'Usuarios, roles y permisos por módulo', 'nucleo', 1),
  ('M21', 'Reportes y estadísticas', 'Ventas, gastos, utilidad, productos más vendidos', 'nucleo', 1),
  ('M22', 'Membresías y planes', 'Mensualidades, control de asistencia, vencimientos', 'activable', 3),
  ('M23', 'Series y garantías', 'IMEI o número de serie, garantía por venta', 'activable', 2),
  ('M24', 'Cotizaciones', 'Proformas que se convierten en venta', 'activable', 2),
  ('M25', 'Compras a productores (acopio)', 'Compra por peso con descuentos por humedad e impureza, liquidación de compra', 'activable', 3),
  ('M26', 'Reservas por fecha', 'Reserva de habitaciones, canchas, salones o artículos por fecha/hora', 'activable', 3)
on conflict (codigo) do update set nombre = excluded.nombre, descripcion = excluded.descripcion, tipo = excluded.tipo, fase = excluded.fase;

insert into catalogo.modulo_dependencia (modulo, requiere) values
  ('M05', 'M04'),
  ('M06', 'M04'),
  ('M07', 'M04'),
  ('M08', 'M04'),
  ('M15', 'M04'),
  ('M16', 'M04'),
  ('M23', 'M04'),
  ('M25', 'M04'),
  ('M25', 'M15'),
  ('M09', 'M08')
on conflict do nothing;

insert into catalogo.plan_modulo (plan, modulo) values
  ('gratis', 'M01'),
  ('gratis', 'M02'),
  ('gratis', 'M03'),
  ('gratis', 'M14'),
  ('gratis', 'M21'),
  ('emprendedor', 'M01'),
  ('emprendedor', 'M02'),
  ('emprendedor', 'M03'),
  ('emprendedor', 'M14'),
  ('emprendedor', 'M21'),
  ('emprendedor', 'M04'),
  ('emprendedor', 'M05'),
  ('emprendedor', 'M06'),
  ('emprendedor', 'M07'),
  ('negocio', 'M01'),
  ('negocio', 'M02'),
  ('negocio', 'M03'),
  ('negocio', 'M14'),
  ('negocio', 'M21'),
  ('negocio', 'M04'),
  ('negocio', 'M05'),
  ('negocio', 'M06'),
  ('negocio', 'M07'),
  ('negocio', 'M15'),
  ('negocio', 'M19'),
  ('negocio', 'M20'),
  ('pro', 'M01'),
  ('pro', 'M02'),
  ('pro', 'M03'),
  ('pro', 'M04'),
  ('pro', 'M05'),
  ('pro', 'M06'),
  ('pro', 'M07'),
  ('pro', 'M08'),
  ('pro', 'M09'),
  ('pro', 'M10'),
  ('pro', 'M11'),
  ('pro', 'M12'),
  ('pro', 'M13'),
  ('pro', 'M14'),
  ('pro', 'M15'),
  ('pro', 'M16'),
  ('pro', 'M17'),
  ('pro', 'M18'),
  ('pro', 'M19'),
  ('pro', 'M20'),
  ('pro', 'M21'),
  ('pro', 'M22'),
  ('pro', 'M23'),
  ('pro', 'M24'),
  ('pro', 'M25'),
  ('pro', 'M26')
on conflict do nothing;

insert into catalogo.familia (codigo, nombre, descripcion, palabra_items, unidad_defecto) values
  ('F01', 'Restaurantes con servicio a mesa', 'Atención en mesa, cocina con comandas', 'Platos', 'Unidad'),
  ('F02', 'Comida rápida y para llevar', 'Venta rápida en mostrador, combos, delivery', 'Productos', 'Unidad'),
  ('F03', 'Panadería, pastelería y producción', 'Producen lo que venden; recetas e insumos', 'Productos', 'Unidad'),
  ('F04', 'Abarrotes y mercado', 'Muchos productos, fiado, venta por peso', 'Productos', 'Unidad'),
  ('F05', 'Moda y retail con variantes', 'Tallas y colores, temporadas', 'Productos', 'Unidad'),
  ('F06', 'Retail general', 'Tiendas y bazares sin variantes complejas', 'Productos', 'Unidad'),
  ('F07', 'Farmacia y salud con producto', 'Lotes, caducidad, control de medicamentos', 'Productos', 'Unidad'),
  ('F08', 'Tecnología y electrónica', 'Series/IMEI, garantías, servicio técnico', 'Productos', 'Unidad'),
  ('F09', 'Ferretería y construcción', 'Miles de ítems, medidas, proformas, crédito', 'Productos', 'Unidad'),
  ('F10', 'Servicios con cita', 'Belleza, bienestar y salud con agenda', 'Servicios', 'Servicio'),
  ('F11', 'Talleres y servicio técnico', 'Órdenes de trabajo, repuestos y mano de obra', 'Servicios', 'Servicio'),
  ('F12', 'Servicios profesionales', 'Honorarios, proyectos, cobros recurrentes', 'Servicios', 'Servicio'),
  ('F13', 'Mayoristas y distribuidoras', 'Volumen, listas de precio, crédito a clientes', 'Productos', 'Caja'),
  ('F14', 'Agro y acopio', 'Insumos agrícolas y compra de producción por peso', 'Productos', 'Quintal'),
  ('F15', 'Deporte, educación y membresías', 'Mensualidades y asistencia', 'Planes', 'Mes'),
  ('F16', 'Hospedaje, eventos y alquiler', 'Reservas por fecha y alquiler de artículos', 'Servicios', 'Noche')
on conflict (codigo) do update set nombre = excluded.nombre, descripcion = excluded.descripcion, palabra_items = excluded.palabra_items, unidad_defecto = excluded.unidad_defecto, version = catalogo.familia.version + 1;

insert into catalogo.familia_modulo (familia, modulo, modo) values
  ('F01', 'M01', 'S'),
  ('F01', 'M02', 'S'),
  ('F01', 'M03', 'S'),
  ('F01', 'M04', 'S'),
  ('F01', 'M08', 'S'),
  ('F01', 'M09', 'S'),
  ('F01', 'M10', 'S'),
  ('F01', 'M14', 'S'),
  ('F01', 'M15', 'S'),
  ('F01', 'M16', 'O'),
  ('F01', 'M18', 'O'),
  ('F01', 'M19', 'S'),
  ('F01', 'M20', 'S'),
  ('F01', 'M21', 'S'),
  ('F02', 'M01', 'S'),
  ('F02', 'M02', 'S'),
  ('F02', 'M03', 'S'),
  ('F02', 'M04', 'S'),
  ('F02', 'M08', 'S'),
  ('F02', 'M09', 'O'),
  ('F02', 'M10', 'S'),
  ('F02', 'M14', 'O'),
  ('F02', 'M15', 'S'),
  ('F02', 'M18', 'O'),
  ('F02', 'M19', 'S'),
  ('F02', 'M20', 'S'),
  ('F02', 'M21', 'S'),
  ('F03', 'M01', 'S'),
  ('F03', 'M02', 'S'),
  ('F03', 'M03', 'S'),
  ('F03', 'M04', 'S'),
  ('F03', 'M08', 'S'),
  ('F03', 'M10', 'O'),
  ('F03', 'M14', 'S'),
  ('F03', 'M15', 'S'),
  ('F03', 'M16', 'S'),
  ('F03', 'M18', 'O'),
  ('F03', 'M19', 'S'),
  ('F03', 'M20', 'S'),
  ('F03', 'M21', 'S'),
  ('F03', 'M24', 'O'),
  ('F04', 'M01', 'S'),
  ('F04', 'M02', 'S'),
  ('F04', 'M03', 'S'),
  ('F04', 'M04', 'S'),
  ('F04', 'M06', 'S'),
  ('F04', 'M07', 'S'),
  ('F04', 'M14', 'S'),
  ('F04', 'M15', 'S'),
  ('F04', 'M16', 'S'),
  ('F04', 'M17', 'O'),
  ('F04', 'M18', 'O'),
  ('F04', 'M19', 'S'),
  ('F04', 'M20', 'S'),
  ('F04', 'M21', 'S'),
  ('F05', 'M01', 'S'),
  ('F05', 'M02', 'S'),
  ('F05', 'M03', 'S'),
  ('F05', 'M04', 'S'),
  ('F05', 'M05', 'S'),
  ('F05', 'M07', 'S'),
  ('F05', 'M14', 'O'),
  ('F05', 'M15', 'S'),
  ('F05', 'M17', 'O'),
  ('F05', 'M18', 'O'),
  ('F05', 'M19', 'S'),
  ('F05', 'M20', 'S'),
  ('F05', 'M21', 'S'),
  ('F06', 'M01', 'S'),
  ('F06', 'M02', 'S'),
  ('F06', 'M03', 'S'),
  ('F06', 'M04', 'S'),
  ('F06', 'M05', 'O'),
  ('F06', 'M07', 'S'),
  ('F06', 'M14', 'O'),
  ('F06', 'M15', 'S'),
  ('F06', 'M17', 'O'),
  ('F06', 'M18', 'O'),
  ('F06', 'M19', 'S'),
  ('F06', 'M20', 'S'),
  ('F06', 'M21', 'S'),
  ('F07', 'M01', 'S'),
  ('F07', 'M02', 'S'),
  ('F07', 'M03', 'S'),
  ('F07', 'M04', 'S'),
  ('F07', 'M07', 'S'),
  ('F07', 'M14', 'O'),
  ('F07', 'M15', 'S'),
  ('F07', 'M16', 'S'),
  ('F07', 'M17', 'O'),
  ('F07', 'M19', 'S'),
  ('F07', 'M20', 'S'),
  ('F07', 'M21', 'S'),
  ('F08', 'M01', 'S'),
  ('F08', 'M02', 'S'),
  ('F08', 'M03', 'S'),
  ('F08', 'M04', 'S'),
  ('F08', 'M07', 'S'),
  ('F08', 'M13', 'O'),
  ('F08', 'M14', 'O'),
  ('F08', 'M15', 'S'),
  ('F08', 'M19', 'S'),
  ('F08', 'M20', 'S'),
  ('F08', 'M21', 'S'),
  ('F08', 'M23', 'S'),
  ('F08', 'M24', 'O'),
  ('F09', 'M01', 'S'),
  ('F09', 'M02', 'S'),
  ('F09', 'M03', 'S'),
  ('F09', 'M04', 'S'),
  ('F09', 'M06', 'S'),
  ('F09', 'M07', 'S'),
  ('F09', 'M14', 'S'),
  ('F09', 'M15', 'S'),
  ('F09', 'M17', 'S'),
  ('F09', 'M18', 'O'),
  ('F09', 'M19', 'S'),
  ('F09', 'M20', 'S'),
  ('F09', 'M21', 'S'),
  ('F09', 'M24', 'S'),
  ('F10', 'M01', 'S'),
  ('F10', 'M02', 'S'),
  ('F10', 'M03', 'S'),
  ('F10', 'M04', 'O'),
  ('F10', 'M11', 'S'),
  ('F10', 'M12', 'S'),
  ('F10', 'M14', 'S'),
  ('F10', 'M18', 'O'),
  ('F10', 'M19', 'S'),
  ('F10', 'M20', 'S'),
  ('F10', 'M21', 'S'),
  ('F11', 'M01', 'S'),
  ('F11', 'M02', 'S'),
  ('F11', 'M03', 'S'),
  ('F11', 'M04', 'S'),
  ('F11', 'M12', 'O'),
  ('F11', 'M13', 'S'),
  ('F11', 'M14', 'S'),
  ('F11', 'M15', 'S'),
  ('F11', 'M19', 'S'),
  ('F11', 'M20', 'S'),
  ('F11', 'M21', 'S'),
  ('F11', 'M24', 'S'),
  ('F12', 'M01', 'S'),
  ('F12', 'M02', 'S'),
  ('F12', 'M03', 'S'),
  ('F12', 'M11', 'O'),
  ('F12', 'M14', 'S'),
  ('F12', 'M19', 'S'),
  ('F12', 'M20', 'S'),
  ('F12', 'M21', 'S'),
  ('F12', 'M24', 'S'),
  ('F13', 'M01', 'S'),
  ('F13', 'M02', 'S'),
  ('F13', 'M03', 'S'),
  ('F13', 'M04', 'S'),
  ('F13', 'M06', 'O'),
  ('F13', 'M07', 'S'),
  ('F13', 'M14', 'S'),
  ('F13', 'M15', 'S'),
  ('F13', 'M16', 'O'),
  ('F13', 'M17', 'S'),
  ('F13', 'M18', 'O'),
  ('F13', 'M19', 'S'),
  ('F13', 'M20', 'S'),
  ('F13', 'M21', 'S'),
  ('F13', 'M24', 'S'),
  ('F14', 'M01', 'S'),
  ('F14', 'M02', 'S'),
  ('F14', 'M03', 'S'),
  ('F14', 'M04', 'S'),
  ('F14', 'M06', 'S'),
  ('F14', 'M14', 'S'),
  ('F14', 'M15', 'S'),
  ('F14', 'M16', 'S'),
  ('F14', 'M17', 'O'),
  ('F14', 'M19', 'S'),
  ('F14', 'M20', 'S'),
  ('F14', 'M21', 'S'),
  ('F14', 'M25', 'O'),
  ('F15', 'M01', 'S'),
  ('F15', 'M02', 'S'),
  ('F15', 'M03', 'S'),
  ('F15', 'M04', 'O'),
  ('F15', 'M11', 'O'),
  ('F15', 'M14', 'S'),
  ('F15', 'M19', 'S'),
  ('F15', 'M20', 'S'),
  ('F15', 'M21', 'S'),
  ('F15', 'M22', 'S'),
  ('F15', 'M26', 'O'),
  ('F16', 'M01', 'S'),
  ('F16', 'M02', 'S'),
  ('F16', 'M03', 'S'),
  ('F16', 'M04', 'O'),
  ('F16', 'M10', 'O'),
  ('F16', 'M14', 'S'),
  ('F16', 'M19', 'S'),
  ('F16', 'M20', 'S'),
  ('F16', 'M21', 'S'),
  ('F16', 'M24', 'S'),
  ('F16', 'M26', 'S')
on conflict (familia, modulo) do update set modo = excluded.modo;

insert into catalogo.tipo_negocio (codigo, nombre, familia, sinonimos, categorias, palabra_items, unidad, ajuste, prioridad) values
  ('T001', 'Restaurante', 'F01', array['almuerzos', 'comedor', 'comida', 'restaurant']::text[], array['Entradas', 'Platos fuertes', 'Bebidas', 'Postres']::text[], 'Platos', 'Unidad', null, 4),
  ('T002', 'Cevichería', 'F01', array['ceviche', 'mariscos']::text[], array['Ceviches', 'Mariscos', 'Bebidas', 'Acompañantes']::text[], 'Platos', 'Unidad', null, 0),
  ('T003', 'Marisquería', 'F01', array['mariscos']::text[], array['Encocados', 'Arroces', 'Ceviches', 'Bebidas']::text[], 'Platos', 'Unidad', null, 0),
  ('T004', 'Picantería', 'F01', array['comida típica']::text[], array['Platos típicos', 'Bebidas', 'Entradas']::text[], 'Platos', 'Unidad', null, 0),
  ('T005', 'Asadero', 'F01', array['pollo asado', 'parrilla']::text[], array['Pollos', 'Parrilladas', 'Acompañantes', 'Bebidas']::text[], 'Platos', 'Unidad', null, 0),
  ('T006', 'Parrillada / steakhouse', 'F01', array['carnes', 'parrilla']::text[], array['Cortes', 'Parrilladas', 'Guarniciones', 'Bebidas']::text[], 'Platos', 'Unidad', null, 0),
  ('T007', 'Chifa', 'F01', array['comida china']::text[], array['Arroces', 'Tallarines', 'Sopas', 'Bebidas']::text[], 'Platos', 'Unidad', null, 0),
  ('T008', 'Pizzería', 'F01', array['pizza']::text[], array['Pizzas', 'Entradas', 'Bebidas', 'Postres']::text[], 'Platos', 'Unidad', 'Tamaños de pizza como variantes', 0),
  ('T009', 'Restaurante de almuerzos (menú del día)', 'F01', array['almuerzos ejecutivos', 'comedor popular']::text[], array['Almuerzos', 'Meriendas', 'Jugos']::text[], 'Platos', 'Unidad', 'Menú del día cambiante', 0),
  ('T010', 'Encebollados y desayunos', 'F01', array['encebollado', 'bolones']::text[], array['Encebollados', 'Bolones', 'Desayunos', 'Bebidas']::text[], 'Platos', 'Unidad', null, 0),
  ('T011', 'Fritadería / hornado', 'F01', array['fritada', 'hornado']::text[], array['Fritada', 'Hornado', 'Acompañantes', 'Bebidas']::text[], 'Platos', 'Unidad', null, 0),
  ('T012', 'Sushi / comida japonesa', 'F01', array['sushi']::text[], array['Rolls', 'Entradas', 'Bebidas']::text[], 'Platos', 'Unidad', null, 0),
  ('T013', 'Restaurante vegetariano', 'F01', array['vegano']::text[], array['Platos', 'Ensaladas', 'Jugos', 'Postres']::text[], 'Platos', 'Unidad', null, 0),
  ('T014', 'Bar / cantina', 'F01', array['bar', 'cervecería']::text[], array['Cervezas', 'Licores', 'Cócteles', 'Piqueos']::text[], 'Platos', 'Unidad', null, 0),
  ('T015', 'Discoteca', 'F01', array['club nocturno']::text[], array['Botellas', 'Tragos', 'Cervezas', 'Entradas/cover']::text[], 'Platos', 'Unidad', null, 0),
  ('T016', 'Karaoke', 'F01', array['karaoke bar']::text[], array['Bebidas', 'Piqueos', 'Horas de sala']::text[], 'Platos', 'Unidad', null, 0),
  ('T017', 'Restaurante de comida internacional', 'F01', array['mexicana', 'italiana']::text[], array['Entradas', 'Platos fuertes', 'Bebidas', 'Postres']::text[], 'Platos', 'Unidad', null, 0),
  ('T018', 'Restaurante de hostería / campestre', 'F01', array['campestre']::text[], array['Platos típicos', 'Parrilladas', 'Bebidas']::text[], 'Platos', 'Unidad', null, 0),
  ('T019', 'Comida rápida', 'F02', array['fast food', 'comidas', 'picadas']::text[], array['Hamburguesas', 'Hot dogs', 'Combos', 'Bebidas']::text[], 'Productos', 'Unidad', null, 4),
  ('T020', 'Hamburguesería', 'F02', array['hamburguesas']::text[], array['Hamburguesas', 'Papas', 'Combos', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T021', 'Salchipapería', 'F02', array['salchipapas']::text[], array['Salchipapas', 'Combos', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T022', 'Food truck', 'F02', array['carrito de comida']::text[], array['Platos', 'Combos', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T023', 'Pollo broaster', 'F02', array['pollo frito']::text[], array['Presas', 'Combos', 'Acompañantes', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T024', 'Cafetería', 'F02', array['café', 'coffee shop']::text[], array['Cafés', 'Bebidas frías', 'Postres', 'Sánduches']::text[], 'Productos', 'Unidad', null, 3),
  ('T025', 'Heladería', 'F02', array['helados']::text[], array['Helados', 'Copas', 'Bebidas', 'Toppings']::text[], 'Productos', 'Unidad', null, 0),
  ('T026', 'Juguería', 'F02', array['jugos', 'batidos']::text[], array['Jugos', 'Batidos', 'Ensaladas de frutas']::text[], 'Productos', 'Unidad', null, 0),
  ('T027', 'Comida casera a domicilio', 'F02', array['almuerzos a domicilio']::text[], array['Almuerzos', 'Postres', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T028', 'Snacks y bocaditos', 'F02', array['piqueos']::text[], array['Bocaditos', 'Snacks', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T029', 'Empanadas y humitas', 'F02', array['humitas', 'tamales', 'empanadas']::text[], array['Empanadas', 'Humitas', 'Tamales', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T030', 'Bolonería', 'F02', array['bolones']::text[], array['Bolones', 'Tigrillo', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T031', 'Cocina solo delivery (dark kitchen)', 'F02', array['cocina fantasma']::text[], array['Platos', 'Combos', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T032', 'Bar escolar / kiosco de colegio', 'F02', array['bar escolar']::text[], array['Snacks', 'Bebidas', 'Almuerzos']::text[], 'Productos', 'Unidad', null, 0),
  ('T033', 'Panadería', 'F03', array['pan']::text[], array['Panes', 'Pasteles', 'Bebidas', 'Lácteos']::text[], 'Productos', 'Unidad', null, 3),
  ('T034', 'Pastelería', 'F03', array['tortas', 'repostería']::text[], array['Tortas', 'Postres', 'Bocaditos', 'Pedidos especiales']::text[], 'Productos', 'Unidad', 'Pedidos con anticipo', 0),
  ('T035', 'Repostería en casa', 'F03', array['tortas por encargo']::text[], array['Tortas', 'Cupcakes', 'Postres']::text[], 'Productos', 'Unidad', 'Pedidos con anticipo', 0),
  ('T036', 'Chocolatería artesanal', 'F03', array['chocolates', 'cacao']::text[], array['Barras', 'Bombones', 'Bebidas de cacao']::text[], 'Productos', 'Unidad', null, 0),
  ('T037', 'Fábrica de helados', 'F03', array['paletas']::text[], array['Paletas', 'Litros', 'Conos']::text[], 'Productos', 'Unidad', null, 0),
  ('T038', 'Producción de snacks', 'F03', array['chifles', 'maduritos']::text[], array['Chifles', 'Snacks', 'Paquetes']::text[], 'Productos', 'Unidad', null, 0),
  ('T039', 'Embutidos artesanales', 'F03', array['chorizos']::text[], array['Embutidos', 'Carnes curadas']::text[], 'Productos', 'Kilo', null, 0),
  ('T040', 'Quesera / lácteos artesanales', 'F03', array['quesos', 'yogurt']::text[], array['Quesos', 'Yogurt', 'Leche']::text[], 'Productos', 'Kilo', null, 0),
  ('T041', 'Cervecería artesanal', 'F03', array['cerveza artesanal']::text[], array['Cervezas', 'Growlers', 'Barriles']::text[], 'Productos', 'Litro', null, 0),
  ('T042', 'Licores artesanales', 'F03', array['destilería']::text[], array['Licores', 'Botellas']::text[], 'Productos', 'Botella', null, 0),
  ('T043', 'Mermeladas y conservas', 'F03', array['conservas']::text[], array['Mermeladas', 'Conservas', 'Salsas']::text[], 'Productos', 'Unidad', null, 0),
  ('T044', 'Catering', 'F03', array['comida para eventos']::text[], array['Menús', 'Bocaditos', 'Servicio']::text[], 'Productos', 'Unidad', 'Cotizaciones por evento', 0),
  ('T045', 'Tienda de barrio', 'F04', array['tienda', 'abarrotes', 'tiendita', 'víveres', 'despensa']::text[], array['Abarrotes', 'Bebidas', 'Lácteos', 'Aseo', 'Snacks']::text[], 'Productos', 'Unidad', null, 5),
  ('T046', 'Minimarket', 'F04', array['minisúper']::text[], array['Abarrotes', 'Bebidas', 'Lácteos', 'Aseo', 'Congelados']::text[], 'Productos', 'Unidad', null, 4),
  ('T047', 'Supermercado pequeño', 'F04', array['autoservicio']::text[], array['Abarrotes', 'Frutas y verduras', 'Carnes', 'Aseo', 'Bebidas']::text[], 'Productos', 'Unidad', null, 0),
  ('T048', 'Despensa / víveres', 'F04', array['víveres']::text[], array['Granos', 'Aceites', 'Enlatados', 'Aseo']::text[], 'Productos', 'Unidad', null, 0),
  ('T049', 'Frutería y verdulería', 'F04', array['frutas y verduras']::text[], array['Frutas', 'Verduras', 'Tubérculos']::text[], 'Productos', 'Kilo', null, 0),
  ('T050', 'Carnicería / tercena', 'F04', array['carnes', 'tercena']::text[], array['Res', 'Cerdo', 'Pollo', 'Embutidos']::text[], 'Productos', 'Libra', null, 0),
  ('T051', 'Pescadería', 'F04', array['mariscos', 'pescado']::text[], array['Pescados', 'Camarón', 'Mariscos']::text[], 'Productos', 'Libra', null, 0),
  ('T052', 'Avícola / venta de pollos', 'F04', array['pollos', 'huevos']::text[], array['Pollo entero', 'Presas', 'Huevos']::text[], 'Productos', 'Libra', null, 0),
  ('T053', 'Charcutería', 'F04', array['embutidos', 'quesos']::text[], array['Embutidos', 'Quesos', 'Fiambres']::text[], 'Productos', 'Kilo', null, 0),
  ('T054', 'Licorería', 'F04', array['licores']::text[], array['Cervezas', 'Licores', 'Vinos', 'Snacks']::text[], 'Productos', 'Unidad', null, 0),
  ('T055', 'Venta de agua y gas', 'F04', array['bidones', 'cilindros']::text[], array['Agua', 'Gas', 'Recargas']::text[], 'Productos', 'Unidad', 'Envases retornables', 0),
  ('T056', 'Tienda naturista', 'F04', array['productos naturales']::text[], array['Suplementos', 'Hierbas', 'Granos']::text[], 'Productos', 'Unidad', null, 0),
  ('T057', 'Venta de huevos', 'F04', array['huevos']::text[], array['Huevos', 'Cubetas']::text[], 'Productos', 'Cubeta', null, 0),
  ('T058', 'Puesto de mercado', 'F04', array['mercado municipal']::text[], array['Productos del puesto']::text[], 'Productos', 'Kilo', null, 0),
  ('T059', 'Granos y cereales', 'F04', array['granos']::text[], array['Arroz', 'Granos', 'Harinas']::text[], 'Productos', 'Quintal', null, 0),
  ('T060', 'Alimento para mascotas', 'F04', array['balanceado de mascotas']::text[], array['Alimento perro', 'Alimento gato', 'Accesorios']::text[], 'Productos', 'Kilo', null, 0),
  ('T061', 'Tienda de ropa', 'F05', array['boutique', 'ropa', 'prendas', 'vestir']::text[], array['Damas', 'Caballeros', 'Niños', 'Accesorios']::text[], 'Productos', 'Unidad', null, 4),
  ('T062', 'Zapatería', 'F05', array['zapatos', 'calzado']::text[], array['Damas', 'Caballeros', 'Niños', 'Deportivo']::text[], 'Productos', 'Unidad', null, 3),
  ('T063', 'Ropa deportiva', 'F05', array['deportes']::text[], array['Camisetas', 'Pantalonetas', 'Calzado', 'Accesorios']::text[], 'Productos', 'Unidad', null, 0),
  ('T064', 'Ropa de bebé y niños', 'F05', array['infantil']::text[], array['Bebés', 'Niñas', 'Niños', 'Accesorios']::text[], 'Productos', 'Unidad', null, 0),
  ('T065', 'Lencería', 'F05', array['ropa interior']::text[], array['Brasieres', 'Panties', 'Pijamas']::text[], 'Productos', 'Unidad', null, 0),
  ('T066', 'Uniformes', 'F05', array['uniformes escolares', 'corporativos']::text[], array['Escolares', 'Corporativos', 'Deportivos']::text[], 'Productos', 'Unidad', 'Pedidos por institución', 0),
  ('T067', 'Venta de ropa por redes', 'F05', array['venta por Instagram', 'TikTok']::text[], array['Prendas', 'Accesorios']::text[], 'Productos', 'Unidad', 'Catálogo online activo', 0),
  ('T068', 'Bolsos y carteras', 'F05', array['carteras']::text[], array['Carteras', 'Mochilas', 'Billeteras']::text[], 'Productos', 'Unidad', null, 0),
  ('T069', 'Sastrería / trajes', 'F05', array['sastre', 'trajes']::text[], array['Trajes', 'Camisas', 'Arreglos']::text[], 'Productos', 'Unidad', 'Arreglos como servicio', 0),
  ('T070', 'Ropa de segunda mano', 'F05', array['ropa usada', 'americana']::text[], array['Prendas', 'Calzado']::text[], 'Productos', 'Unidad', null, 0),
  ('T071', 'Óptica', 'F05', array['lentes', 'gafas']::text[], array['Monturas', 'Lentes', 'Gafas de sol', 'Exámenes']::text[], 'Productos', 'Unidad', null, 0),
  ('T072', 'Joyería / bisutería', 'F05', array['joyas']::text[], array['Anillos', 'Collares', 'Aretes', 'Relojes']::text[], 'Productos', 'Unidad', null, 0),
  ('T073', 'Bazar', 'F06', array['variedades']::text[], array['Hogar', 'Plásticos', 'Regalos', 'Útiles']::text[], 'Productos', 'Unidad', null, 3),
  ('T074', 'Papelería y útiles escolares', 'F06', array['papelería']::text[], array['Útiles', 'Cuadernos', 'Oficina', 'Copias']::text[], 'Productos', 'Unidad', null, 3),
  ('T075', 'Librería', 'F06', array['libros']::text[], array['Libros', 'Revistas', 'Papelería']::text[], 'Productos', 'Unidad', null, 0),
  ('T076', 'Tienda de regalos', 'F06', array['regalos', 'detalles']::text[], array['Regalos', 'Peluches', 'Tarjetas', 'Globos']::text[], 'Productos', 'Unidad', null, 0),
  ('T077', 'Juguetería', 'F06', array['juguetes']::text[], array['Juguetes', 'Juegos', 'Didácticos']::text[], 'Productos', 'Unidad', null, 0),
  ('T078', 'Artículos para el hogar', 'F06', array['hogar']::text[], array['Cocina', 'Baño', 'Decoración', 'Limpieza']::text[], 'Productos', 'Unidad', null, 0),
  ('T079', 'Plásticos y desechables', 'F06', array['desechables']::text[], array['Desechables', 'Plásticos', 'Fundas']::text[], 'Productos', 'Unidad', null, 0),
  ('T080', 'Cosméticos y perfumería', 'F06', array['cosméticos', 'perfumes']::text[], array['Maquillaje', 'Cuidado de piel', 'Perfumes']::text[], 'Productos', 'Unidad', null, 0),
  ('T081', 'Productos de limpieza', 'F06', array['químicos de limpieza']::text[], array['Detergentes', 'Desinfectantes', 'Utensilios']::text[], 'Productos', 'Galón', null, 0),
  ('T082', 'Floristería', 'F06', array['flores', 'arreglos']::text[], array['Arreglos', 'Ramos', 'Plantas']::text[], 'Productos', 'Unidad', 'Pedidos con fecha de entrega', 0),
  ('T083', 'Artesanías', 'F06', array['artesanías']::text[], array['Artesanías', 'Souvenirs']::text[], 'Productos', 'Unidad', null, 0),
  ('T084', 'Pet shop (accesorios)', 'F06', array['mascotas']::text[], array['Accesorios', 'Juguetes', 'Higiene']::text[], 'Productos', 'Unidad', null, 0),
  ('T085', 'Artículos deportivos', 'F06', array['deportes']::text[], array['Balones', 'Implementos', 'Ropa']::text[], 'Productos', 'Unidad', null, 0),
  ('T086', 'Mueblería', 'F06', array['muebles']::text[], array['Salas', 'Comedores', 'Dormitorios']::text[], 'Productos', 'Unidad', 'Venta a crédito', 0),
  ('T087', 'Colchones', 'F06', array['colchonería']::text[], array['Colchones', 'Almohadas', 'Bases']::text[], 'Productos', 'Unidad', null, 0),
  ('T088', 'Accesorios de moda', 'F06', array['bisutería menor']::text[], array['Aretes', 'Pulseras', 'Accesorios de cabello']::text[], 'Productos', 'Unidad', null, 0),
  ('T089', 'Artículos de fiesta', 'F06', array['cotillón']::text[], array['Globos', 'Decoración', 'Piñatas']::text[], 'Productos', 'Unidad', null, 0),
  ('T090', 'Tabaquería / vape shop', 'F06', array['tabaco']::text[], array['Productos', 'Accesorios']::text[], 'Productos', 'Unidad', null, 0),
  ('T091', 'Souvenirs turísticos', 'F06', array['recuerdos']::text[], array['Souvenirs', 'Camisetas', 'Artesanías']::text[], 'Productos', 'Unidad', null, 0),
  ('T092', 'Bicicletas', 'F06', array['bici']::text[], array['Bicicletas', 'Repuestos', 'Accesorios']::text[], 'Productos', 'Unidad', null, 0),
  ('T093', 'Farmacia', 'F07', array['botica']::text[], array['Medicamentos', 'Cuidado personal', 'Bebé', 'Primeros auxilios']::text[], 'Productos', 'Unidad', 'Venta por unidad o caja (fracción)', 4),
  ('T094', 'Farmacia veterinaria', 'F07', array['veterinaria de mascotas']::text[], array['Medicamentos', 'Vacunas', 'Alimentos']::text[], 'Productos', 'Unidad', null, 0),
  ('T095', 'Insumos médicos', 'F07', array['distribuidora médica']::text[], array['Insumos', 'Equipos', 'Descartables']::text[], 'Productos', 'Unidad', null, 0),
  ('T096', 'Suplementos deportivos', 'F07', array['proteína', 'nutrición deportiva']::text[], array['Proteínas', 'Vitaminas', 'Snacks']::text[], 'Productos', 'Unidad', null, 0),
  ('T097', 'Ortopedia', 'F07', array['artículos ortopédicos']::text[], array['Plantillas', 'Fajas', 'Sillas de ruedas']::text[], 'Productos', 'Unidad', null, 0),
  ('T098', 'Homeopatía / productos naturales', 'F07', array['naturista']::text[], array['Suplementos', 'Tés', 'Aceites']::text[], 'Productos', 'Unidad', null, 0),
  ('T099', 'Tienda de celulares', 'F08', array['celulares', 'móviles']::text[], array['Celulares', 'Accesorios', 'Chips', 'Recargas']::text[], 'Productos', 'Unidad', 'IMEI obligatorio', 3),
  ('T100', 'Accesorios para celulares', 'F08', array['fundas', 'cargadores']::text[], array['Fundas', 'Cargadores', 'Audífonos', 'Micas']::text[], 'Productos', 'Unidad', null, 0),
  ('T101', 'Computadoras', 'F08', array['computación']::text[], array['Laptops', 'Componentes', 'Periféricos']::text[], 'Productos', 'Unidad', null, 0),
  ('T102', 'Electrodomésticos', 'F08', array['línea blanca']::text[], array['Refrigeración', 'Cocina', 'Lavado', 'Pequeños']::text[], 'Productos', 'Unidad', 'Venta a crédito', 0),
  ('T103', 'Videojuegos', 'F08', array['gaming']::text[], array['Consolas', 'Juegos', 'Accesorios']::text[], 'Productos', 'Unidad', null, 0),
  ('T104', 'Cámaras de seguridad / CCTV', 'F08', array['seguridad electrónica']::text[], array['Cámaras', 'DVR', 'Instalación']::text[], 'Productos', 'Unidad', null, 0),
  ('T105', 'Cyber / centro de cómputo', 'F08', array['internet', 'copias']::text[], array['Horas de internet', 'Impresiones', 'Copias']::text[], 'Productos', 'Unidad', 'Cobro por tiempo', 0),
  ('T106', 'Recargas y pagos de servicios', 'F08', array['punto de recargas']::text[], array['Recargas', 'Pagos de servicios', 'Chips']::text[], 'Productos', 'Unidad', 'Comisión por transacción', 0),
  ('T107', 'Electrónica y componentes', 'F08', array['componentes electrónicos']::text[], array['Componentes', 'Cables', 'Herramientas']::text[], 'Productos', 'Unidad', null, 0),
  ('T108', 'Energía solar', 'F08', array['paneles solares']::text[], array['Paneles', 'Baterías', 'Inversores', 'Instalación']::text[], 'Productos', 'Unidad', null, 0),
  ('T109', 'Ferretería', 'F09', array['ferretería']::text[], array['Herramientas', 'Tornillería', 'Plomería', 'Eléctricos', 'Pintura']::text[], 'Productos', 'Unidad', null, 4),
  ('T110', 'Materiales de construcción', 'F09', array['bloques', 'cemento']::text[], array['Cemento', 'Hierro', 'Bloques', 'Arena']::text[], 'Productos', 'Quintal', null, 0),
  ('T111', 'Pinturas', 'F09', array['tienda de pinturas']::text[], array['Pinturas', 'Brochas', 'Diluyentes']::text[], 'Productos', 'Galón', null, 0),
  ('T112', 'Materiales eléctricos', 'F09', array['eléctricos']::text[], array['Cables', 'Breakers', 'Iluminación']::text[], 'Productos', 'Metro', null, 0),
  ('T113', 'Cerrajería', 'F09', array['llaves', 'cerraduras']::text[], array['Cerraduras', 'Copias de llaves', 'Instalación']::text[], 'Productos', 'Unidad', null, 0),
  ('T114', 'Vidriería y aluminio', 'F09', array['vidrios']::text[], array['Vidrios', 'Aluminio', 'Instalación']::text[], 'Productos', 'Metro', null, 0),
  ('T115', 'Cerámica y acabados', 'F09', array['porcelanato', 'baldosas']::text[], array['Pisos', 'Paredes', 'Sanitarios']::text[], 'Productos', 'Metro cuadrado', null, 0),
  ('T116', 'Maderera / aserradero', 'F09', array['madera']::text[], array['Tablas', 'Tablones', 'Triplex']::text[], 'Productos', 'Unidad', null, 0),
  ('T117', 'Plomería y sanitarios', 'F09', array['gasfitería']::text[], array['Tubos', 'Accesorios', 'Sanitarios']::text[], 'Productos', 'Unidad', null, 0),
  ('T118', 'Hierro y metales', 'F09', array['ferro']::text[], array['Varillas', 'Tubos', 'Planchas']::text[], 'Productos', 'Quintal', null, 0),
  ('T119', 'Peluquería', 'F10', array['salón de belleza']::text[], array['Cortes', 'Tintes', 'Tratamientos', 'Productos']::text[], 'Servicios', 'Servicio', null, 4),
  ('T120', 'Barbería', 'F10', array['barber']::text[], array['Cortes', 'Barba', 'Productos']::text[], 'Servicios', 'Servicio', null, 3),
  ('T121', 'Spa', 'F10', array['masajes']::text[], array['Masajes', 'Faciales', 'Paquetes']::text[], 'Servicios', 'Servicio', null, 0),
  ('T122', 'Manicure y uñas', 'F10', array['uñas']::text[], array['Manicure', 'Pedicure', 'Uñas acrílicas']::text[], 'Servicios', 'Servicio', null, 0),
  ('T123', 'Centro de estética', 'F10', array['estética']::text[], array['Faciales', 'Depilación', 'Tratamientos']::text[], 'Servicios', 'Servicio', null, 0),
  ('T124', 'Pestañas y cejas', 'F10', array['lash']::text[], array['Extensiones', 'Laminado', 'Diseño de cejas']::text[], 'Servicios', 'Servicio', null, 0),
  ('T125', 'Tatuajes y piercing', 'F10', array['tattoo']::text[], array['Tatuajes', 'Piercings', 'Cuidado']::text[], 'Servicios', 'Servicio', 'Anticipo por cita', 0),
  ('T126', 'Consultorio médico', 'F10', array['médico']::text[], array['Consultas', 'Procedimientos', 'Certificados']::text[], 'Servicios', 'Servicio', 'Ficha de paciente', 0),
  ('T127', 'Consultorio odontológico', 'F10', array['dentista']::text[], array['Consultas', 'Limpieza', 'Tratamientos']::text[], 'Servicios', 'Servicio', 'Plan de tratamiento por paciente', 0),
  ('T128', 'Clínica veterinaria', 'F10', array['veterinario']::text[], array['Consultas', 'Vacunas', 'Baño y peluquería', 'Productos']::text[], 'Servicios', 'Servicio', 'Ficha de mascota', 0),
  ('T129', 'Psicología / terapia', 'F10', array['terapeuta']::text[], array['Sesiones', 'Evaluaciones']::text[], 'Servicios', 'Servicio', null, 0),
  ('T130', 'Fisioterapia', 'F10', array['rehabilitación']::text[], array['Sesiones', 'Paquetes']::text[], 'Servicios', 'Servicio', null, 0),
  ('T131', 'Nutricionista', 'F10', array['nutrición']::text[], array['Consultas', 'Planes']::text[], 'Servicios', 'Servicio', null, 0),
  ('T132', 'Laboratorio clínico', 'F10', array['exámenes']::text[], array['Exámenes', 'Perfiles']::text[], 'Servicios', 'Servicio', null, 0),
  ('T133', 'Peluquería canina', 'F10', array['grooming']::text[], array['Baño', 'Corte', 'Productos']::text[], 'Servicios', 'Servicio', null, 0),
  ('T134', 'Masajes a domicilio', 'F10', array['masajista']::text[], array['Masajes', 'Paquetes']::text[], 'Servicios', 'Servicio', null, 0),
  ('T135', 'Maquillaje profesional', 'F10', array['maquilladora']::text[], array['Maquillaje social', 'Novias', 'Clases']::text[], 'Servicios', 'Servicio', null, 0),
  ('T136', 'Fotografía', 'F10', array['fotógrafo', 'estudio']::text[], array['Sesiones', 'Impresiones', 'Paquetes']::text[], 'Servicios', 'Servicio', null, 0),
  ('T137', 'Taller mecánico', 'F11', array['mecánica automotriz']::text[], array['Mano de obra', 'Repuestos', 'Lubricantes']::text[], 'Servicios', 'Servicio', 'Ficha de vehículo por placa', 3),
  ('T138', 'Lubricadora', 'F11', array['cambio de aceite']::text[], array['Aceites', 'Filtros', 'Servicios']::text[], 'Servicios', 'Servicio', 'Recordatorio por kilometraje', 0),
  ('T139', 'Lavadora de autos', 'F11', array['car wash']::text[], array['Lavados', 'Pulido', 'Aspirado']::text[], 'Servicios', 'Servicio', null, 0),
  ('T140', 'Vulcanizadora / llantera', 'F11', array['llantas']::text[], array['Llantas', 'Parches', 'Balanceo']::text[], 'Servicios', 'Servicio', null, 0),
  ('T141', 'Taller de motos', 'F11', array['motos']::text[], array['Mano de obra', 'Repuestos', 'Lubricantes']::text[], 'Servicios', 'Servicio', null, 0),
  ('T142', 'Repuestos automotrices', 'F11', array['repuestos']::text[], array['Repuestos', 'Lubricantes', 'Accesorios']::text[], 'Servicios', 'Servicio', null, 0),
  ('T143', 'Servicio técnico de celulares', 'F11', array['reparación de celulares']::text[], array['Pantallas', 'Baterías', 'Reparaciones']::text[], 'Servicios', 'Servicio', null, 0),
  ('T144', 'Servicio técnico de computadoras', 'F11', array['reparación de pc']::text[], array['Mantenimiento', 'Reparaciones', 'Repuestos']::text[], 'Servicios', 'Servicio', null, 0),
  ('T145', 'Reparación de electrodomésticos', 'F11', array['técnico línea blanca']::text[], array['Reparaciones', 'Repuestos']::text[], 'Servicios', 'Servicio', null, 0),
  ('T146', 'Tapicería', 'F11', array['tapicero']::text[], array['Tapizado', 'Materiales']::text[], 'Servicios', 'Servicio', null, 0),
  ('T147', 'Carpintería', 'F11', array['muebles a medida']::text[], array['Muebles', 'Materiales', 'Mano de obra']::text[], 'Servicios', 'Servicio', null, 0),
  ('T148', 'Metalmecánica / soldadura', 'F11', array['soldador']::text[], array['Trabajos', 'Materiales']::text[], 'Servicios', 'Servicio', null, 0),
  ('T149', 'Costura y arreglos', 'F11', array['modista']::text[], array['Arreglos', 'Confección']::text[], 'Servicios', 'Servicio', null, 0),
  ('T150', 'Reparación de calzado', 'F11', array['zapatero']::text[], array['Reparaciones', 'Accesorios']::text[], 'Servicios', 'Servicio', null, 0),
  ('T151', 'Imprenta y serigrafía', 'F11', array['imprenta', 'gigantografías']::text[], array['Impresiones', 'Tarjetas', 'Serigrafía', 'Gigantografías']::text[], 'Servicios', 'Servicio', null, 0),
  ('T152', 'Lavandería', 'F11', array['lavado de ropa']::text[], array['Lavado por kilo', 'Planchado', 'Edredones']::text[], 'Servicios', 'Kilo', null, 0),
  ('T153', 'Refrigeración y aire acondicionado', 'F11', array['técnico de aire']::text[], array['Instalación', 'Mantenimiento', 'Repuestos']::text[], 'Servicios', 'Servicio', null, 0),
  ('T154', 'Electricista / instalaciones', 'F11', array['eléctrico']::text[], array['Instalaciones', 'Materiales']::text[], 'Servicios', 'Servicio', null, 0),
  ('T155', 'Estudio contable', 'F12', array['contador']::text[], array['Declaraciones', 'Contabilidad mensual', 'Asesorías']::text[], 'Servicios', 'Servicio', 'Cobro mensual recurrente', 0),
  ('T156', 'Estudio jurídico', 'F12', array['abogado']::text[], array['Consultas', 'Trámites', 'Patrocinio']::text[], 'Servicios', 'Servicio', null, 0),
  ('T157', 'Agencia de marketing', 'F12', array['publicidad']::text[], array['Manejo de redes', 'Diseño', 'Campañas']::text[], 'Servicios', 'Servicio', null, 0),
  ('T158', 'Diseño gráfico', 'F12', array['diseñador']::text[], array['Logos', 'Artes', 'Paquetes']::text[], 'Servicios', 'Servicio', null, 0),
  ('T159', 'Consultoría', 'F12', array['consultor']::text[], array['Horas', 'Proyectos']::text[], 'Servicios', 'Servicio', null, 0),
  ('T160', 'Arquitectura e ingeniería', 'F12', array['arquitecto', 'ingeniero']::text[], array['Planos', 'Diseños', 'Supervisión']::text[], 'Servicios', 'Servicio', null, 0),
  ('T161', 'Agencia de viajes', 'F12', array['turismo']::text[], array['Paquetes', 'Boletos', 'Tours']::text[], 'Servicios', 'Servicio', null, 0),
  ('T162', 'Agente de seguros', 'F12', array['seguros']::text[], array['Pólizas', 'Renovaciones']::text[], 'Servicios', 'Servicio', null, 0),
  ('T163', 'Bienes raíces', 'F12', array['inmobiliaria']::text[], array['Ventas', 'Arriendos', 'Comisiones']::text[], 'Servicios', 'Servicio', null, 0),
  ('T164', 'Servicios de limpieza', 'F12', array['limpieza']::text[], array['Hogar', 'Oficinas', 'Limpieza profunda']::text[], 'Servicios', 'Servicio', null, 0),
  ('T165', 'Transporte y fletes', 'F12', array['mudanzas', 'carga']::text[], array['Fletes', 'Mudanzas', 'Encomiendas']::text[], 'Servicios', 'Servicio', null, 0),
  ('T166', 'Courier / encomiendas', 'F12', array['envíos']::text[], array['Envíos locales', 'Nacionales']::text[], 'Servicios', 'Servicio', null, 0),
  ('T167', 'Trámites y gestoría', 'F12', array['tramitador']::text[], array['Trámites', 'Matriculación']::text[], 'Servicios', 'Servicio', null, 0),
  ('T168', 'Desarrollo de software / TI', 'F12', array['programador']::text[], array['Proyectos', 'Soporte', 'Hosting']::text[], 'Servicios', 'Servicio', null, 0),
  ('T169', 'Seguridad privada', 'F12', array['guardianía']::text[], array['Servicio mensual', 'Eventos']::text[], 'Servicios', 'Servicio', null, 0),
  ('T170', 'Distribuidora de abarrotes', 'F13', array['mayorista de abarrotes']::text[], array['Abarrotes', 'Bebidas', 'Aseo']::text[], 'Productos', 'Caja', null, 0),
  ('T171', 'Distribuidora de bebidas', 'F13', array['bebidas al por mayor']::text[], array['Gaseosas', 'Aguas', 'Cervezas', 'Energizantes']::text[], 'Productos', 'Caja', null, 0),
  ('T172', 'Distribuidora de licores', 'F13', array['licores al por mayor']::text[], array['Licores', 'Cervezas', 'Vinos']::text[], 'Productos', 'Caja', null, 0),
  ('T173', 'Distribuidora de snacks y confites', 'F13', array['confites']::text[], array['Snacks', 'Caramelos', 'Galletas']::text[], 'Productos', 'Caja', null, 0),
  ('T174', 'Distribuidora de limpieza', 'F13', array['químicos al por mayor']::text[], array['Limpieza', 'Aseo personal']::text[], 'Productos', 'Caja', null, 0),
  ('T175', 'Distribuidora de desechables', 'F13', array['desechables al por mayor']::text[], array['Desechables', 'Fundas', 'Envases']::text[], 'Productos', 'Caja', null, 0),
  ('T176', 'Distribuidora de papelería', 'F13', array['papelería al por mayor']::text[], array['Útiles', 'Papel', 'Oficina']::text[], 'Productos', 'Caja', null, 0),
  ('T177', 'Importadora', 'F13', array['importador']::text[], array['Productos importados']::text[], 'Productos', 'Caja', 'Costos de importación', 0),
  ('T178', 'Venta por catálogo', 'F13', array['revendedora', 'multinivel']::text[], array['Productos del catálogo']::text[], 'Productos', 'Caja', 'Pedidos por campaña', 0),
  ('T179', 'Distribuidora de huevos y lácteos', 'F13', array['lácteos al por mayor']::text[], array['Huevos', 'Leche', 'Quesos']::text[], 'Productos', 'Caja', null, 0),
  ('T180', 'Distribuidora de carnes', 'F13', array['cárnicos']::text[], array['Carnes', 'Embutidos']::text[], 'Productos', 'Kilo', null, 0),
  ('T181', 'Droguería / distribuidora de medicinas', 'F13', array['medicinas al por mayor']::text[], array['Medicamentos', 'Insumos']::text[], 'Productos', 'Caja', null, 0),
  ('T182', 'Almacén agrícola / agroquímicos', 'F14', array['agroquímica', 'insumos agrícolas', 'insumos para el campo', 'agropecuario', 'fertilizantes', 'finca', 'agro']::text[], array['Fertilizantes', 'Herbicidas', 'Fungicidas', 'Semillas']::text[], 'Productos', 'Quintal', null, 4),
  ('T183', 'Agroveterinaria', 'F14', array['veterinaria agropecuaria']::text[], array['Medicinas', 'Vacunas', 'Balanceados', 'Herramientas']::text[], 'Productos', 'Quintal', null, 3),
  ('T184', 'Venta de balanceados', 'F14', array['balanceado']::text[], array['Aves', 'Cerdos', 'Ganado', 'Peces']::text[], 'Productos', 'Quintal', null, 0),
  ('T185', 'Centro de acopio de cacao', 'F14', array['compra de cacao']::text[], array['Cacao en baba', 'Cacao seco']::text[], 'Productos', 'Quintal', 'Compra a productores con descuento por humedad', 0),
  ('T186', 'Piladora de arroz', 'F14', array['piladora']::text[], array['Arroz pilado', 'Arrocillo', 'Polvillo']::text[], 'Productos', 'Quintal', 'Servicio de pilado y compra de arroz en cáscara', 0),
  ('T187', 'Acopio de maíz', 'F14', array['compra de maíz']::text[], array['Maíz amarillo']::text[], 'Productos', 'Quintal', 'Compra a productores con descuento por humedad', 0),
  ('T188', 'Acopio de café', 'F14', array['compra de café']::text[], array['Café en grano', 'Café seco']::text[], 'Productos', 'Quintal', 'Compra a productores', 0),
  ('T189', 'Vivero / semillas y plantas', 'F14', array['vivero']::text[], array['Semillas', 'Plantas', 'Sustratos']::text[], 'Productos', 'Quintal', null, 0),
  ('T190', 'Venta de ganado', 'F14', array['ganadería']::text[], array['Bovinos', 'Porcinos']::text[], 'Productos', 'Quintal', 'Venta por cabeza o por peso', 0),
  ('T191', 'Venta de camarón', 'F14', array['camaronera']::text[], array['Camarón por talla']::text[], 'Productos', 'Libra', null, 0),
  ('T192', 'Venta de banano', 'F14', array['bananera']::text[], array['Cajas de banano']::text[], 'Productos', 'Caja', null, 0),
  ('T193', 'Maquinaria agrícola', 'F14', array['motosierras', 'bombas']::text[], array['Bombas', 'Motosierras', 'Repuestos']::text[], 'Productos', 'Quintal', null, 0),
  ('T194', 'Riego agrícola', 'F14', array['sistemas de riego']::text[], array['Tuberías', 'Aspersores', 'Instalación']::text[], 'Productos', 'Quintal', null, 0),
  ('T195', 'Gimnasio', 'F15', array['gym']::text[], array['Mensualidades', 'Pases diarios', 'Suplementos']::text[], 'Planes', 'Mes', null, 0),
  ('T196', 'Academia de baile', 'F15', array['baile']::text[], array['Mensualidades', 'Clases sueltas']::text[], 'Planes', 'Mes', null, 0),
  ('T197', 'Escuela de fútbol', 'F15', array['club deportivo']::text[], array['Mensualidades', 'Uniformes', 'Torneos']::text[], 'Planes', 'Mes', null, 0),
  ('T198', 'Centro de tutorías', 'F15', array['refuerzo escolar']::text[], array['Mensualidades', 'Clases']::text[], 'Planes', 'Mes', null, 0),
  ('T199', 'Escuela de idiomas', 'F15', array['inglés']::text[], array['Niveles', 'Materiales']::text[], 'Planes', 'Mes', null, 0),
  ('T200', 'Escuela de música', 'F15', array['música']::text[], array['Mensualidades', 'Instrumentos']::text[], 'Planes', 'Mes', null, 0),
  ('T201', 'Guardería / centro infantil', 'F15', array['guardería']::text[], array['Mensualidades', 'Alimentación']::text[], 'Planes', 'Mes', null, 0),
  ('T202', 'Escuela de conducción', 'F15', array['autoescuela']::text[], array['Cursos', 'Clases prácticas']::text[], 'Planes', 'Mes', null, 0),
  ('T203', 'Yoga / pilates / crossfit', 'F15', array['estudio fitness']::text[], array['Membresías', 'Clases']::text[], 'Planes', 'Mes', null, 0),
  ('T204', 'Cancha sintética', 'F15', array['alquiler de canchas']::text[], array['Horas de cancha', 'Bebidas']::text[], 'Planes', 'Hora', 'Reserva por hora', 0),
  ('T205', 'Piscina / balneario', 'F15', array['balneario']::text[], array['Entradas', 'Membresías', 'Bar']::text[], 'Planes', 'Mes', null, 0),
  ('T206', 'Hostal / hotel pequeño', 'F16', array['hospedaje']::text[], array['Habitaciones', 'Desayunos', 'Servicios']::text[], 'Servicios', 'Noche', null, 0),
  ('T207', 'Cabañas / hostería', 'F16', array['hostería']::text[], array['Cabañas', 'Alimentación', 'Actividades']::text[], 'Servicios', 'Noche', null, 0),
  ('T208', 'Salón de eventos', 'F16', array['alquiler de salón']::text[], array['Alquiler', 'Decoración', 'Menaje']::text[], 'Servicios', 'Noche', null, 0),
  ('T209', 'Alquiler de sillas y mesas', 'F16', array['alquiler de menaje']::text[], array['Sillas', 'Mesas', 'Carpas']::text[], 'Servicios', 'Día', null, 0),
  ('T210', 'Organización de eventos', 'F16', array['wedding planner']::text[], array['Paquetes', 'Decoración', 'Coordinación']::text[], 'Servicios', 'Noche', null, 0),
  ('T211', 'Decoración de eventos', 'F16', array['decoradora']::text[], array['Decoración', 'Globos', 'Flores']::text[], 'Servicios', 'Noche', null, 0),
  ('T212', 'Alquiler de vehículos', 'F16', array['rent a car']::text[], array['Vehículos']::text[], 'Servicios', 'Día', null, 0),
  ('T213', 'Alquiler de trajes y disfraces', 'F16', array['disfraces']::text[], array['Trajes', 'Disfraces']::text[], 'Servicios', 'Día', null, 0),
  ('T214', 'Inflables y juegos infantiles', 'F16', array['brincolines']::text[], array['Inflables', 'Juegos']::text[], 'Servicios', 'Día', null, 0),
  ('T215', 'Tours y turismo local', 'F16', array['operadora turística']::text[], array['Tours', 'Paquetes', 'Transporte']::text[], 'Servicios', 'Noche', null, 0),
  ('T216', 'Parqueadero', 'F16', array['estacionamiento']::text[], array['Por hora', 'Mensualidad']::text[], 'Servicios', 'Hora', null, 0)
on conflict (codigo) do update set nombre = excluded.nombre, familia = excluded.familia, sinonimos = excluded.sinonimos, categorias = excluded.categorias, palabra_items = excluded.palabra_items, unidad = excluded.unidad, ajuste = excluded.ajuste, prioridad = excluded.prioridad, version = catalogo.tipo_negocio.version + 1;

insert into catalogo.plantilla_producto (tipo_negocio_id, categoria, nombre, unidad, variantes, orden)
select tn.id, v.categoria, v.nombre, v.unidad, v.variantes, v.orden from (values
  ('T045', 'Abarrotes', 'Arroz 1 kg', 'Unidad', null, 1),
  ('T045', 'Abarrotes', 'Azúcar 1 kg', 'Unidad', null, 2),
  ('T045', 'Abarrotes', 'Aceite 1 L', 'Unidad', null, 3),
  ('T045', 'Abarrotes', 'Atún en lata', 'Unidad', null, 4),
  ('T045', 'Bebidas', 'Gaseosa 1.35 L', 'Unidad', null, 5),
  ('T045', 'Bebidas', 'Agua 625 ml', 'Unidad', null, 6),
  ('T045', 'Lácteos', 'Leche 1 L', 'Unidad', null, 7),
  ('T045', 'Lácteos', 'Queso fresco', 'Libra', null, 8),
  ('T045', 'Aseo', 'Papel higiénico x4', 'Unidad', null, 9),
  ('T045', 'Aseo', 'Detergente 500 g', 'Unidad', null, 10),
  ('T045', 'Snacks', 'Papas fritas', 'Unidad', null, 11),
  ('T045', 'Panadería', 'Pan', 'Unidad', null, 12),
  ('T002', 'Ceviches', 'Ceviche de camarón', 'Plato', null, 1),
  ('T002', 'Ceviches', 'Ceviche de pescado', 'Plato', null, 2),
  ('T002', 'Ceviches', 'Ceviche mixto', 'Plato', null, 3),
  ('T002', 'Mariscos', 'Arroz marinero', 'Plato', null, 4),
  ('T002', 'Mariscos', 'Encocado de pescado', 'Plato', null, 5),
  ('T002', 'Acompañantes', 'Chifles', 'Porción', null, 6),
  ('T002', 'Acompañantes', 'Canguil', 'Porción', null, 7),
  ('T002', 'Bebidas', 'Cerveza', 'Unidad', null, 8),
  ('T002', 'Bebidas', 'Jugo natural', 'Vaso', null, 9),
  ('T002', 'Bebidas', 'Gaseosa personal', 'Unidad', null, 10),
  ('T119', 'Cortes', 'Corte dama', 'Servicio', null, 1),
  ('T119', 'Cortes', 'Corte caballero', 'Servicio', null, 2),
  ('T119', 'Tintes', 'Tinte completo', 'Servicio', null, 3),
  ('T119', 'Tintes', 'Mechas / balayage', 'Servicio', null, 4),
  ('T119', 'Tratamientos', 'Keratina', 'Servicio', null, 5),
  ('T119', 'Tratamientos', 'Hidratación', 'Servicio', null, 6),
  ('T119', 'Peinados', 'Cepillado', 'Servicio', null, 7),
  ('T119', 'Peinados', 'Peinado de evento', 'Servicio', null, 8),
  ('T119', 'Productos', 'Shampoo', 'Unidad', null, 9),
  ('T119', 'Productos', 'Acondicionador', 'Unidad', null, 10),
  ('T182', 'Fertilizantes', 'Urea 50 kg', 'Saco', null, 1),
  ('T182', 'Fertilizantes', 'DAP 50 kg', 'Saco', null, 2),
  ('T182', 'Fertilizantes', 'Muriato de potasio 50 kg', 'Saco', null, 3),
  ('T182', 'Herbicidas', 'Herbicida sistémico 1 L', 'Litro', null, 4),
  ('T182', 'Herbicidas', 'Herbicida de contacto 1 L', 'Litro', null, 5),
  ('T182', 'Fungicidas', 'Fungicida cúprico 1 kg', 'Kilo', null, 6),
  ('T182', 'Insecticidas', 'Insecticida 1 L', 'Litro', null, 7),
  ('T182', 'Semillas', 'Semilla de maíz', 'Saco', null, 8),
  ('T182', 'Semillas', 'Semilla de arroz', 'Saco', null, 9),
  ('T182', 'Herramientas', 'Machete', 'Unidad', null, 10),
  ('T182', 'Herramientas', 'Bomba de fumigar 20 L', 'Unidad', null, 11),
  ('T137', 'Mano de obra', 'Diagnóstico', 'Servicio', null, 1),
  ('T137', 'Mano de obra', 'Afinamiento', 'Servicio', null, 2),
  ('T137', 'Mano de obra', 'Cambio de pastillas', 'Servicio', null, 3),
  ('T137', 'Mano de obra', 'ABC de frenos', 'Servicio', null, 4),
  ('T137', 'Repuestos', 'Pastillas de freno', 'Juego', null, 5),
  ('T137', 'Repuestos', 'Filtro de aceite', 'Unidad', null, 6),
  ('T137', 'Repuestos', 'Filtro de aire', 'Unidad', null, 7),
  ('T137', 'Repuestos', 'Bujías', 'Juego', null, 8),
  ('T137', 'Lubricantes', 'Aceite de motor 20W50', 'Galón', null, 9),
  ('T137', 'Lubricantes', 'Líquido de frenos', 'Unidad', null, 10),
  ('T061', 'Damas', 'Blusa', 'Unidad', 'Talla S/M/L · color', 1),
  ('T061', 'Damas', 'Jean dama', 'Unidad', 'Talla 26-36', 2),
  ('T061', 'Damas', 'Vestido', 'Unidad', 'Talla · color', 3),
  ('T061', 'Caballeros', 'Camisa', 'Unidad', 'Talla S-XL · color', 4),
  ('T061', 'Caballeros', 'Jean caballero', 'Unidad', 'Talla 28-40', 5),
  ('T061', 'Caballeros', 'Camiseta', 'Unidad', 'Talla · color', 6),
  ('T061', 'Niños', 'Conjunto infantil', 'Unidad', 'Talla 2-12', 7),
  ('T061', 'Accesorios', 'Correa', 'Unidad', null, 8),
  ('T061', 'Accesorios', 'Gorra', 'Unidad', null, 9)
) as v(codigo, categoria, nombre, unidad, variantes, orden)
join catalogo.tipo_negocio tn on tn.codigo = v.codigo
on conflict (tipo_negocio_id, nombre) do update set categoria = excluded.categoria, unidad = excluded.unidad, variantes = excluded.variantes, orden = excluded.orden;
